#!/bin/sh

# POST-COMMIT HOOK

REPOS=$1
REV=$2
UUID=`svnlook uuid $REPOS`

/usr/bin/curl \
  -v \
  --connect-timeout 5\
  --header "Content-Type:text/plain;charset=UTF-8" \
  --data "`svnlook changed --revision $REV $REPOS`" \
http://hoved.dcs.gla.ac.uk:8080/subversion/${UUID}/notifyCommit?rev=$REV